### PR TITLE
Move phpmailer/phpmailer to suggest

### LINKED ISSUE #296: Move phpmailer to suggests
I would like to propose that the below is moved to the composer `suggest` list https://github.com/sebastianfeldmann/phpbu/blob/81624ce079009b33cfc27105db55f21d81739077/composer.json#L53 

As far as I'm aware, https://github.com/sebastianfeldmann/phpbu/blob/main/src/Log/Mail.php is the only usage and if you don't configure it via [logging](http://phpbu.de/manual/current/en/logging.html) it's not used.

@sebastianfeldmann what do you think?

### PR DESCRIPTION
**Pull request by bytestream**
Closes #296

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Adding it to `require-dev` is perfect but you haven't added it to the `suggest` part of the Composer configuration :)

**Comment by bytestream** [comment]
> Adding it to `require-dev` is perfect but you haven't added it to the `suggest` part of the Composer configuration :)

Thanks for the quick reply. I've updated it so it's in both `require-dev` and `suggest`

**Comment by sebastianfeldmann** [comment]
Thanks :)

**Comment by bytestream** [comment]
:fearful: would you like a separate PR which fixes the tests? :sweat_smile: 

Also, is it worth testing on PHP 7.2 given that's listed as the composer minimum required php version?

**Comment by sebastianfeldmann** [comment]
Since PHP 7.2 is not officially supported anymore and should not be used so I don't thing it is necessary to run tests for php 7.2 :)

**Pull request merged**
