### PR TITLE
Add --events flag to mysqldump

### PR DESCRIPTION
**Pull request by stevenrombauts**
This PR adds an option to include the --events flag to the mysqldump command.

### CODE REVIEW

**Review by sebastianfeldmann — APPROVED** [review]
Looks good!
Thanks

**Comment by stevenrombauts** [comment]
@sebastianfeldmann That was fast! Thanks for accepting this PR.  What would you recommend we do to update our phpbu version to include this change now? Should be build the phar ourselves, or is there a way to download it from the main branch directly in some way?

**Comment by sebastianfeldmann** [comment]
I tag and release an new version this afternoon.
Think that's the easiest way ;)

**Comment by sebastianfeldmann** [comment]
I just released version 6.0.13.

Thanks again :)

**Pull request merged**
