### PR TITLE
WIP: Remote cleanup

### PR DESCRIPTION
**Pull request by vitalybaev**
I decided to open a pull request (work in progress) for completing this feature.
What's done:
1. Classes renamed as you told.
2. Remote sync fired by `Sync` classes, not by runner
3. Display information about remote cleaning up in simulate

What plan to do:
- [x] Write some tests
- [x] FTP
- [x] SFTP
- [x] Amazon S3 (v3)
- [x] Check for code style
- [x] Find and fix potential bugs

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Hi Vitaly,
that looks great!
I would rename `getSimulateInfo` to something more descriptive like `getCleanupOutput`, `getClearableInfo` or even do it like this

```php
public function simulate(Target $target, Result $result)
{
    ...
    $this->simulateRemoteCleanup($targer, $result);
}
```
Thinking about it, I think that's the way to go. What do you think.

**Comment by vitalybaev** [comment]
Oh, yes, naming isn't my best quality :)
I guess `simulateRemoteCleanup` in `Clearable` would be great!

**Comment by vitalybaev** [comment]
Amazon S3 v3 remote sync pushed!

**Comment by vitalybaev** [comment]
Have resolved conflicts, but please make sure that I have correct. Thanks!

**Comment by vitalybaev** [comment]
@sebastianfeldmann what about code style? How it's important for now? And what rules I should follow?
Scrutinizer marks lines like
```
$result->debug('checking size to be at least ' . $value . PHP_EOL);
```
should be
```
$result->debug('checking size to be at least '.$value.PHP_EOL);
```

Is it right?

**Comment by sebastianfeldmann** [comment]
I just checked, there are a lot of `phpcs` errors all over the place. So I would suggest we ignore them for now and clean them up after a merge with a single code style commit.

But it should be 
```php
$result->debug('checking size to be at least ' . $value . PHP_EOL);
```
:)

**Comment by vitalybaev** [comment]
Okay, tomorrow I’ll make FTP cleanup.
Other adapters will come later after merge, because I never worked with them before, is it ok?

**Comment by sebastianfeldmann** [comment]
Yeah of course, not all adapters have to support remote cleanup. Awesome that you do AWS, XFTP, and Dropbox

**Comment by vitalybaev** [comment]
I've done with FTP cleanup. Also I added FlySystem as dependency so it would be more simple in future to work with different adapters in future. And for now FTP sync and cleanup uses FlySystem.
Please check, thanks!

**Comment by vitalybaev** [comment]
Oh, got you. I saw your issue about that. So I'll revert FTP to work without FlySystem soon!

**Comment by sebastianfeldmann** [comment]
oO I see, I have to delete this issue, when I created it I thought if someone already uses `FlySyststem` it would be easy to just use it as well and phoooooof it magically just works.
Sadly that's not how it works ;)

**Comment by sebastianfeldmann** [comment]
I added the passive mode documentation for the upcoming version 5.1 https://github.com/sebastianfeldmann/phpbu-documentation/blob/4142d7aa8853f074f9278563592fe078a85bd7bf/src/5.1/en/sync.xml#L526

I used `passive` instead of `passive_mode` maybe you could rename that on your end as well ;)

I added the new `OpenStack` documentation. https://github.com/sebastianfeldmann/phpbu-documentation/blob/4142d7aa8853f074f9278563592fe078a85bd7bf/src/5.1/en/sync.xml#L258

Further more I started documenting the remote cleanup feature. https://github.com/sebastianfeldmann/phpbu-documentation/blob/4142d7aa8853f074f9278563592fe078a85bd7bf/src/5.1/en/sync.xml#L130

I'll add the cleanup options to the other relevant `Sync` adapters so the docs are ready to be published if we publish version 5.1.0

**Comment by vitalybaev** [comment]
Docs look good! I renamed to `passive` and completely removed FlySystem.
So for now the only remaining things - think about writing tests and test cleanups manually (I do it all the time, but there are a lot of changes)

**Comment by sebastianfeldmann** [comment]
Since the `Sync` stuff is the weakest tested code right now, testing remote cleanups is not going to be any easier.

It would be great if you would write the `Collector` and `File` unit test. 

The unit test changes I did for the `Sftp` sync seems promising.
If we could change the code, so that we have a dedicated `protected` methods that create and return the Dropbox api client or the AWS client like the `login` method return the FTP client. We could mock those methods and make them return configured mock objects and then even run the `sync` method via unit test.

So if you want, you can ignore the `Sync` unit tests so far, I will handle those after the final merge.

**Comment by vitalybaev** [comment]
I don't want to ignore tests at all, and will write some simple unit tests :)
So, after that I guess we could merge, but we'll have to make coverage better in future!

**Comment by vitalybaev** [comment]
Completed writing unit test for collectors and files, wait for your feedback :)

**Comment by vitalybaev** [comment]
I guess it's quite ready for merge 👍
But we'll continue to improve it.

**Comment by sebastianfeldmann** [comment]
As soon as I am back on WIFI, I will pull your changes and have a look at them ;)

**Comment by vitalybaev** [comment]
Added one more little thing :)

**Comment by sebastianfeldmann** [comment]
Good that I didn’t merge it this morning ;)

**Comment by vitalybaev** [comment]
So, for now I've checked common notices from Scrutinizer/PHPStorm. Tested all stuff, I've added.
Other improvements could be in future PRs

**Comment by sebastianfeldmann** [comment]
You mean let Clearable define an abstract getCleaner method that each Sync has to implement if it uses Clearable?

**Comment by vitalybaev** [comment]
In `Clearable`:
```php
/**
 * Execute the remote clean up if needed
 *
 * @param \phpbu\App\Backup\Target $target
 * @param \phpbu\App\Result        $result
 */
public function cleanup(Target $target, Result $result)
{
    if (!$this->cleaner) {
        return;
    }

    $collector = $this->createCollector($target);
    $this->cleaner->cleanup($target, $collector, $result);
}
```

In `Sync\AmazonS3v3` for example:
1) Remove method `cleanup` since it located in `Clearable`
2) Define method for receiving collector:
```php
/**
 * Creates collector for Amazon S3
 *
 * @param \phpbu\App\Backup\Target $target
 * @return \phpbu\App\Backup\Collector
 */
protected function createCollector(Target $target): Collector
{
    return new \phpbu\App\Backup\Collector\AmazonS3v3($target, $this->client, $this->bucket, $this->path);
}
```

**Comment by vitalybaev** [comment]
I could push the code, I’ll look at it and if we decide I’ll revert the commit

**Comment by vitalybaev** [comment]
But I guess need of such approach have to be.
Because why we should allow implement `cleanup` method with checks and running cleanup (with possible mistakes in implementation and duplicating) if we only have to get proper collector for cleanup.

**Comment by sebastianfeldmann** [comment]
I think I like it, will have a more detailed look at it when I’m back on may laptop

**Comment by sebastianfeldmann** [comment]
And yes you are 100% right, all that is different for each sync remote cleanup is the collector.

**Comment by vitalybaev** [comment]
Okay, I'll push my code and you'll take a look when you could.
Then we decide what to do with that - revert, change or other

**Comment by vitalybaev** [comment]
So, I guess it looks good for now.
And I have no other issues to fix currently

**Comment by vitalybaev** [comment]
Oh 🤦‍♂️ I've found some old empty `cleanup` methods in `Sync` classes that doesn't support remote cleanup.
That's all, I promise 😄

**Comment by vitalybaev** [comment]
🎉🎉🎉🎉🎉

**Comment by sebastianfeldmann** [comment]
Merged 🎉 👻 🎉

**Comment by sebastianfeldmann** [comment]
Hi, I fixed all phpcs issues and added a lot of PHPDoc.
To execute phpcs locally just execute `ant phpcs`

Can you please have a look at this https://scrutinizer-ci.com/g/sebastianfeldmann/phpbu/inspections/3b1fb0db-4f76-4e1f-abf7-55cf550ef196/issues/files/src/Backup/File/OpenStack.php?status=new&orderField=path&order=asc&honorSelectedPaths=0 ;)

**Comment by vitalybaev** [comment]
Great!
About this issue - it’s mistake in php-openstack PHPDoc. As you can see I’ve already sent pull request to them and it was meged, but not released for now

**Comment by sebastianfeldmann** [comment]
What can I say, you rock ;)

**Comment by vitalybaev** [comment]
Oh, it’s not a rocket science 😀

**Comment by sebastianfeldmann** [comment]
Hi Vitaly,

I checked the remote `Collectors` and it seems they are not working a 100%.

I'm currently investigating it, maybe you can have a look as well.
https://github.com/sebastianfeldmann/phpbu/issues/144

**Pull request merged**
