### PR TITLE
Remote collectors with placeholder path

### PR DESCRIPTION
**Pull request by vitalybaev**
Hi there!
Done Amazon S3 works fine with placeholder paths.
What do you think about that?

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Current Status: Stuck with a bunch of tourists on a whiskey tour in Scotland :D
As soon as I’m back at the hotel I’ll have a look ;)

**Comment by sebastianfeldmann** [comment]
I’m not sure if a Trait is the right solution.
I think I would prefere to duplicate the code for now if necessary and wait for a clearer picture after implementing all remote collectors.
If that’s not too much to ask, could you undo the Path trait and put whatever you need in the remote collector?

I think we will find a better solution if we just accept the duplication for now.

**Comment by vitalybaev** [comment]
Sure, I've removed `Path` trait.
And I have some idea - maybe it would be great to make `Path` class, that could have all of needed methods and use it in Target/Collector or everywhere?
So we could extract all logic of path to this class and will not duplicate this logic. Also it's not a trait and it would be better by architecture.

What do you think?

**Comment by vitalybaev** [comment]
I've pushed this idea. For now `Path` class used in collector and we could use it in Target as well.
I guess it's a right way:
1) We have small separate class that does exactly one thing
2) We don't duplicate logic of this by reusing class
3) We don't make code more complicated
4) This is quite testable

And you are right, trait didn't right way at all

**Comment by sebastianfeldmann** [comment]
Yes I was thinking about something similar when I did the local `Collector` fix. I actually had a `Path` class but wasn't sure enough so I didn't use it and sticked with the simple solution.

But as you said, I think we will end up with something like this.

**Comment by sebastianfeldmann** [comment]
And there you go again, already implemented it ;)

Sweet!

**Comment by vitalybaev** [comment]
Okay, tomorrow I'll change `Target` to use `Path` class, check tests, write tests for `Path` as well and rewrite other Collectors for placeholders logic.

> And there you go again, already implemented it ;)

I just like to try almost any concept in my brain :)

**Comment by vitalybaev** [comment]
Look at my last commit. It's some idea I'd like to share.
The reason is about `validateConfig` method, that used in two `Sync` classes and one in place implementation in `SoftLayer` sync class.
1) created `phpbu\App\Backup\Sync` abstract class with `validateConfig` method implemented
2) `Sync` interface moved to `phpbu\App\Backup\Sync\Sync` (not a great idea, but I've stucked with factory tests with rsync)
3) rewritten checking config in Sync classes. Also for now this method used by `Dropbox` to simplify it's setUp method.

**Comment by sebastianfeldmann** [comment]
Nice!

But sorry we CAN’T change or move the Sync interface, it’s the extension point for custom sync classes.

Like I said before, I think it is best to keep some duplication until we did all remote collectors, to make sure we are using the right abstractions.
So to get a better picture it is absolutely fine to have duplicated code in those remote collectors.

Don’t rush it ;)
The right solution will reveal itself sooner or later ;)

**Comment by vitalybaev** [comment]
As I sad - it's not a problem :) It's only for testing some ideas.
Reverted it.

Could you check the code about remote collectors and placeholders, so that I could be sure to continue work for FTP/SFTP and OpenStack collectors?

**Comment by sebastianfeldmann** [comment]
Will do :)

I’ll be on a plane home in a couple of hours and depending on WiFi at the airport it will probably take till tomorrow.

But being at home / work next week I can fully concentrate to get the 5.1 release ready :party:

**Comment by vitalybaev** [comment]
Sure, have a nice flight! :)

**Comment by vitalybaev** [comment]
I've added ability to auth to SFTP via private key. It's very important for me (and not only for me), because all of my 10 servers doesn't support password authentication 😄 
Changes:
1) added config options `private_key` - path to private key file, `private_key_password` - optional
2) for FTP nothing changed, `password` is mandatory
3) for SFTP `password` could be empty if `private_key` is presented

**Comment by sebastianfeldmann** [comment]
Looks good!

**Comment by sebastianfeldmann** [comment]
Man you are on 🔥:D
I’m stuck in a meeting for hours

**Comment by sebastianfeldmann** [comment]
Sweet!

Regarding 2.
I don't get what you mean by "only after replacing placeholders"

I looked at the OpenStack `collect` method and it looked fine.

**Comment by vitalybaev** [comment]
OpenStack collector only looks for files at target directory of current sync (#144 still affected)
My account at Rackspace is currently under verification so I could fix it later

**Comment by vitalybaev** [comment]
For example, if we have path “backups/%Y/%m/target-%H-%i openstack and ftp will scan only “backups/2018/05” dir for now

**Comment by sebastianfeldmann** [comment]
merged ;)

**Comment by sebastianfeldmann** [comment]
Let me take care of `Ftp` if you could fix `OpenStack` that would be awesome

**Comment by vitalybaev** [comment]
Good news! Sure, I’ll fix OpenStack as soon as my rackspace account will be active!

**Pull request merged**
