### PR TITLE
Wasabi S3 Sync

### PR DESCRIPTION
**Pull request by planetahuevo**
Create Wasabi S3 Sync file for #256

### CODE REVIEW

**Review by sebastianfeldmann — APPROVED** [review]
Looks good, I will add the factory index and release it ;)

**Comment by sebastianfeldmann** [comment]
Thanks 👍

**Comment by planetahuevo** [comment]
@sebastianfeldmann Thank you! 
When do you think you will be able to create a new release? 
Not in a hurry, I am just planning ahead. :)

**Comment by planetahuevo** [comment]
@sebastianfeldmann would be possible to get a new release with this? 

Thanks

**Pull request merged**
