### PR TITLE
Add optional color for Plan commands

### PR DESCRIPTION
**Pull request by raphaelts3**
Hello @sebastianfeldmann I was working on some issues related to the restore commands, but I miss the possibility of having colored lines at the restore commands, so I would like to add this optional first and then move with few of the restore options.

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Hi Raphael

First of all thank you for putting in the time and effort.
I'm not sure it useful to let every `Restorable` make decisions about the output coloring. I would argue that it should not be of their concern to worry about the output format.

Do you have a specific use case in mind where you would argue that it makes sense.

Because if you want to add some explanation to commands that you want to display in a different color, I would advice not allowing to handle the coloring, instead I would allow passing in an optional comment for a command.

```php
$plan->addDecryptionCommand($cmd, 'Some comment to explain the command');
```

This way the `Restore` runner could be in charge of the output formatting and the `Plan` stays separated from every IO.

Or do you have other reasons why you want to handle to coloring in every `Restorable`?

**Comment by raphaelts3** [comment]
Hi Sebastian, my idea was just to add some explanations about the comments.

I agree your alternative, it's way more elegant. I could make this change, if it's okay with you.

But could be good to discuss a bit about how to expose the explanation, on my mind it should be like the [BE CAREFUL] line, yellow and starting with '#', or like "actual_command # commentary"
What are your thoughts on this?

**Comment by sebastianfeldmann** [comment]
If you would make the change that would be awesome.

I would put the comment on top.
If we would want to add a '#' in front of the comment this is getting difficult if someone adds multi line comments.

Then it would look like this.

```
# comment line 1
comment line 2

command
```

But I think we can ignore this for now. If we run into this issue it is easily fixable.

For the output I would try something like

    [GRAY]# $comment[/GRAY]
    $command

But I think this can be changed later very easily as well so it doesn't have to be perfect for the pull request.

If you output the commands in the `Restore` runner you should use a `printCommand` method.

```php
class Restore
{
...
    private function printCommand(string $command, string $comment) : void
    {
        if ($comment !== '') {
            echo ...
        }
        echo ...
    }
```

This will cleanup the foreach $commands loops quite a bit and make them much more readable.

And another thought: I would not make `comment` nullable. I think I would prefer something like the following. Just to make sure it is always a string so the `printCommand` method can use not nullable types as well.

```php
public function addRestoreCommand(string $command, string $comment = ''): void
{
     $this->commands['decompress'][] = [
             'comment' => $comment,
             'command' => $command
    ];
}
```

What do you think?

**Comment by raphaelts3** [comment]
Sounds like a solid plan, I will work on it on the next days and submit when I finish.

Thanks for you attention! =)

**Pull request merged**
