### PR TITLE
Initial implementation of mysqldump restore

### LINKED ISSUE #202: Make Mysqldump source restorable
Make `Mysqldump` source  implement the `Restorable` interface similar to the `Tar` source.

### PR DESCRIPTION
**Pull request by rhorber**
I created an implementation of the `restore` method for the `mysqldump` source.
I'm not sure if this is the intended solution, but I tried my best with my (little) knowledge of the code base. Feel free to mention or add suggestions/improvements.

Closes #202.

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Thanks for picking up this "issue".

I think this is a good start. The idea would be to move the `mysql` command creation into its own `Executable\Mysql` class just like it's done with the `OpenSSL` restoring.
https://github.com/sebastianfeldmann/phpbu/blob/ae01614e733123ee5e91f11be20734ab4fd58d31/src/Backup/Crypter/OpenSSL.php#L156 

I'm not sure we should include the `find` command in the output even if it's very handy ;)

**Comment by rhorber** [comment]
Well, that was really not what I wanted to do. I am very sorry.
I did not think about "pull", which reset my master branch (as configured...).

I created a new PR: #216 

To your comment:
I saw the `mysqldump` command but thought I would write the command directly, as in the `tar` restore method. If you agree, I create and add it (to the new PR).
`find` command: Would you prefer to search the table files with PHP and print the commands for each file or do you think of another command? (I can't think of a platform-independent command right now...)

**Comment by sebastianfeldmann** [comment]
I was a bit confuesed what `pull bot` is doing, but don't worry about it :)

Yes if the command is very simple to create like the `tar` command it is fine to just do it inside the `Restorable`. But if it is getting a bit more complicated (e.g. OpenSSL) this should not be handled inside the `Restorable`.

Regarding the `find` command I would not add it and just tell the user what to do.
You now have the ability to add comments to `Plan` commands and could do something like this.

```php
$plan->addRestoreCommand($mysql->getCommand(), 'execute this for every table file');
```

So the endresult looks something like
```
# execute this for every table file
mysql ... TABLEFILE
```

This way the user better understands what kind of command is responsible for restoring the data.
My intention with the `--restore` plan is not to provide a copy paste list of commands. Sometimes it is but that is not the main goal. The main goal is to support the user to understand the mechanics of the restore process.

**Comment by rhorber** [comment]
I was confused too :).

Okay, I will create an `Executable` for `mysql`.

Restore plan: In that case, I got that wrong (I thought of providing copy paste commands, as you noticed). I'll update that. Thanks for the explanations.

**Pull request closed without merging**
