### PR TITLE
Enable phpstan level 2

### PR DESCRIPTION
**Pull request by marcelthole**
And here is the phpstan integration for level 2. See #160 
Idk if you want to add the dependency to your project

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
This is currently a bit difficult because of the TravisCI integration tests that are executed with different PHP versions.
Any idea how to solve this?
Otherwise, I would copy the config to my local directory and put it on the ignore list so I can still execute it locally but do not put it in the dev dependencies and use the PHAR file locally.

**Comment by sebastianfeldmann** [comment]
This is currently a bit difficult because of the TravisCI integration tests that are executed with different PHP versions.
Any idea how to solve this?
Otherwise, I would copy the config to my local directory and put it on the ignore list so I can still execute it locally but do not put it in the dev dependencies and use the PHAR file locally.

**Comment by sebastianfeldmann** [comment]
This is currently a bit difficult because of the TravisCI integration tests that are executed with different PHP versions.
Any idea how to solve this?
Otherwise, I would copy the config to my local directory and put it on the ignore list so I can still execute it locally but do not put it in the dev dependencies and use the PHAR file locally.

**Comment by marcelthole** [comment]
You could run the Travic CI with composer `--ignore-platform-reqs`. But i guess this is not the best Solution. 

The second solution is to just add the `phpstan.neon` File and add a separate Testcase on Travis-CI with PHP 7.1 and phpstan as phar.

```yml
before_script:
# [...]
- if [ $TRAVIS_PHP_VERSION = "7.1" ]; then wget -O phpstan.phar https://github.com/phpstan/phpstan/releases/download/0.10.5/phpstan.phar ; fi
script:
# [...]
- if [ $TRAVIS_PHP_VERSION = "7.1" ]; then php phpstan.phar analyse --no-progress -c phpstan.neon; fi
```

Should i update the PR to the second solution?

**Comment by sebastianfeldmann** [comment]
Yes the second solution sounds good

**Pull request merged**
