### PR TITLE
Warn When Using Weak Ciphers

### LINKED ISSUE #153: security: warn when a weak / insecure algorithm is used
I see in the Crypter class that it accepts all algorithms, even (insecure) stream ciphers, ecb mode ciphers and a few others.

I would like to see some warning when one of them is used ;-)

Scott of Paragonie and others block these and enforce a strong and secure algorithm.

### PR DESCRIPTION
**Pull request by moebrowne**
This PR closes #153 by adding a warning when weak ciphers are used.

@DanielRuf could you confirm [the list](https://github.com/moebrowne/phpbu/blob/feature/weak-cipher-warning/src/Backup/Crypter/OpenSSL.php#L58-L91) of weak ciphers is correct?

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Could you move the weak algorithm handing to the `Source`? It feels more like an application feature than a binary/executable feature. With this change you will also eliminate the `phpstan` error during CI ;)

**Comment by moebrowne** [comment]
I think you're right, that logic doesn't belong to the Executable :+1:

**Comment by moebrowne** [comment]
Any thoughts @DanielRuf?

**Comment by DanielRuf** [comment]
Sorry for the late reply. So far the list of weak ciphers looks good (but personally I do not all available ciphers).

**Pull request merged**
