### PR TITLE
Feat/Google Cloud Storage sync

### PR DESCRIPTION
**Pull request by ddattee**
## Description 

Add Google Cloud Storage sync

## To test

1. You need a Google Cloud Storage account
2. Create your own credentials file https://developers.google.com/workspace/guides/create-credentials?hl=fr
3. Update your phpbu config file following the examples in [doc/config/sync/](https://github.com/sebastianfeldmann/phpbu/compare/main...ddattee:phpbu:feat/google-cloud-storage-sync?expand=1#diff-3f8e9556f8d307aaa0d7456c19eb8a034a119dd1b71e7a1b6ce8db27bc40eb87)
4. Run a backup it should upload to the bucket you configured

### CODE REVIEW

**Comment by ddattee** [comment]
Hello hello, any news ? 
Should I update anything missing ?
Thanks !

**Comment by ddattee** [comment]
All right I'll fix the checks ^^

**Comment by sebastianfeldmann** [comment]
Thanks for the PR I will have an in depth look at it hopefully this week :)

**Review by sebastianfeldmann — APPROVED** [review]
Looks great!

**Pull request merged**
