### PR TITLE
Pgdump sslmode

### PR DESCRIPTION
**Pull request by jbouzekri**
Add sslmode option to pgdump to configure the behavior of pg_dump when connecting to a ssl enabled server.

Note : also a fix on 3 tests using removed assert method in phpunit

### CODE REVIEW

**Comment by jbouzekri** [comment]
@sebastianfeldmann : the build fails because of Xdebug 3 per default in travis. I fixed it in one of my own project by using the environement variable XDEBUG_MODE=coverage in my travis job settings

**Comment by sebastianfeldmann** [comment]
Thanks for the hint, I will have a look at it ASAP :)

**Review by sebastianfeldmann — APPROVED** [review]
Looks good ;)

**Comment by sebastianfeldmann** [comment]
Yes will do so ASAP most likely Friday or Saturday

**Pull request merged**
