### PR TITLE
Initial implementation of mysqldump restore

### PR DESCRIPTION
**Pull request by rhorber**
Follow up of #212 (which was closed unintentionally).

### CODE REVIEW

**Comment by rhorber** [comment]
@sebastianfeldmann Would it make sense / bring some advantage to create a MysqlCommon Executable? (Despite some de-duplicated code. But I think the creation of the Executables would not change.)

**Comment by rhorber** [comment]
Hit the button by accident (While writing the above comment). Sorry.

**Comment by sebastianfeldmann** [comment]
Wow thanks. On a first glance this looks really good.
I will have a closer look at it this evening.

**Comment by sebastianfeldmann** [comment]
Thanks a lot :)

**Pull request merged**
