### PR TITLE
YandexDisk implementation

### PR DESCRIPTION
**Pull request by AxelPAL**
To use this you should:
1. Go to https://oauth.yandex.ru/client/new
2. Create your app
2.1 Check all Disks permissions
3. Generate access token:
3.1 Go to https://oauth.yandex.ru/authorize?response_type=token&client_id=APP_ID (replace APP_ID with ID given to you)
3.2 Then you should get token parameter from query parameters of opened page

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Wow that looks great, I'll have a look at it, give it a try and if everything works merge it

**Comment by sebastianfeldmann** [comment]
I'm not sure what to do with that :)
Sadly I'm not able to test that at all :/ 
Getting an account at Yandex seems quite impossible for me since I don't understand russian at all :(
Have you thought about releasing this as a plugin to `phpbu`
I know there is a Yandex plugin available, but that doesn't support remote cleanup as your implementation does.
https://github.com/AxelPAL/phpbu-yandex-disk/blob/master/extend.php

**Comment by AxelPAL** [comment]
I think for this feature it's better to be in the core of your lib. My plugin you mentioned is quite old and should be upgraded. It's much more useful to get this functionality in core. If Yandex doesn't have English version, use can use translators or I can help you with getting the account, creating your own app and using it in phpbu.

**Comment by sebastianfeldmann** [comment]
I'm not disagreeing with you that it would be nice to include it in the core.
Sadly translators aren't helping me that much.
If the account is free I would appreciate your help for setting up an account for `yandex@phpbu.de`.

**Comment by AxelPAL** [comment]
I've sent all needed data to your email.

**Comment by sebastianfeldmann** [comment]
Got it! Thanks will try to figure it out ;)

**Comment by sebastianfeldmann** [comment]
Thank you very much :)

I added the Yandex sync to the latest 5.2.4 release

**Comment by AxelPAL** [comment]
Cool! Also documentation should be updated I suggest 😊

**Pull request merged**
