### PR TITLE
Fixed absolute path for sftp sync

### PR DESCRIPTION
**Pull request by vitalybaev**
I've realized, that if I write absolute path with SFTP sync, it doesn't work.
Problem appears because `Sftp->getRemoteDirectoryList` method exploding path with leading `/` to array with empty string as first element, causing error at `phpseclib\Net\SFTP` line 711.
Also I've added filtering empty parts of path since phpseclib causing error when it happens

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Hi Vitaly,
sorry I was out with food poisoning the last 2 days.

Great jobs once again.

**Comment by sebastianfeldmann** [comment]
Thanks, feeling much better now!

Yes it is ok, since I don't inject the Sftp (PHPSecLib) instance it is hard to mock/test otherwise :)

**Comment by vitalybaev** [comment]
Ok, I saw an issue about integration tests (with Docker for example) when we could really test backups, sync and other, but I'm not sure it worth the effort for now.

**Comment by sebastianfeldmann** [comment]
I'm not sure either, further more I'm not really a "Docker Expert" nor even a regular "Docker User" at all. So this is a thing I'm ignoring for quite some time now ;)

**Comment by vitalybaev** [comment]
I'm using Docker for integration tests at my prod projects (but only with GitLab CI) and it's not so difficult.
So, in the future we could set it up!

Unit testing does big job here and integration tests could help to find bugs only with real execution (like my pull request about wrong argument for mongodump).

**Comment by sebastianfeldmann** [comment]
You are absolutely right :)

**Comment by sebastianfeldmann** [comment]
I made some adjustments to `SftpTest` and managed to make `Sftp::getRemoteDirectoryList` private again.

I accomplished this by mocking the PHPSecLib Sftp creation. For this to work I had to make the `Sftp::login` method protected. I prefer this way because so we don't grant `public` access to internal business logic.

And as the say "Once it's public you gonna maintain it for the rest of your life" ;)

Pushed to master some minutes ago.

**Comment by vitalybaev** [comment]
Hi, sorry about late answer. You are absolutely right!

**Comment by sebastianfeldmann** [comment]
Don't worry about it, hope you are fine.

Sadly this is leading to some conflicts in your WIP pull request. But I think you can resolve those rather quickly.

**Comment by vitalybaev** [comment]
Sure, I gonna sync my master with upstream and merge it into my feature branch, is it ok?

**Comment by sebastianfeldmann** [comment]
Off course

**Pull request merged**
